Support Jade

diff --git a/Scheduler/RT-ROS/script/install b/Scheduler/RT-ROS/script/install
--- a/Scheduler/RT-ROS/script/install
+++ b/Scheduler/RT-ROS/script/install
@@ -7,6 +7,7 @@ cd $script_dir/../clients/roscpp/build/
 cmake ..
 make
 
+<< COMMENTOUT
 # For Ubuntu 14.04 (indigo) 
 if [ -e /opt/ros/indigo/lib/libroscpp.so ]; then
 	if [ ! -e /opt/ros/indigo/lib/libroscpp.so.backup ]; then
@@ -59,5 +60,52 @@ if [ -e /opt/ros/kinetic/lib/libroscpp.so ]; then
 	echo "sudo cp ./devel/lib/libroscpp.so /opt/ros/kinetic/lib/libroscpp.so"
 	# echo "sudo cp ../include/ros/ros.h /opt/ros/kinetic/include/ros/ros.h"
 	echo "sudo cp ../include/ros_rosch/publish_counter.h /opt/ros/kinetic/include/ros_rosch/publish_counter.h"
+fi
+
+COMMENTOUT
+
+
+
+
+
+DISTRIBUTION="NULL"
+
+if [ -e /opt/ros/indigo/lib/libroscpp.so ]; then
+	DISTRIBUTION="indigo"
+elif [ -e /opt/ros/kinetic/lib/libroscpp.so ]; then
+	DISTRIBUTION="kinetic"
+elif [ -e /opt/ros/jade/lib/libroscpp.so ]; then
+	DISTRIBUTION="jade" 
+else
+	echo "libroscpp.so does not found" 
+	echo "Stop uninstall script" 
+	exit 1
+fi
+
+
+if [ -e /opt/ros/${DISTRIBUTION}/lib/libroscpp.so ]; then
+	if [ ! -e /opt/ros/${DISTRIBUTION}/lib/libroscpp.so.backup ]; then
+    echo "-------- Create backup file --------"
+    echo "sudo cp /opt/ros/${DISTRIBUTION}/lib/libroscpp.so /opt/ros/${DISTRIBUTION}/lib/libroscpp.so.backup"
+    sudo cp /opt/ros/${DISTRIBUTION}/lib/libroscpp.so /opt/ros/${DISTRIBUTION}/lib/libroscpp.so.backup
+    echo "------------------------------------"
+	fi
+	if [ ! -e /opt/ros/${DISTRIBUTION}/include/ros/ros.h.backup ]; then
+    echo "-------- Create backup file --------"
+    echo "sudo cp /opt/ros/${DISTRIBUTION}/include/ros/ros.h /opt/ros/${DISTRIBUTION}/include/ros/ros.h.backup"
+    sudo cp /opt/ros/${DISTRIBUTION}/include/ros/ros.h /opt/ros/${DISTRIBUTION}/include/ros/ros.h.backup
+    echo "------------------------------------"
+	fi
+	sudo cp ./devel/lib/libroscpp.so /opt/ros/${DISTRIBUTION}/lib/libroscpp.so
+	# sudo cp ../include/ros/ros.h /opt/ros/${DISTRIBUTION}/include/ros/ros.h
+	if [ ! -e /opt/ros/${DISTRIBUTION}/include/ros_rosch ]; then
+    sudo mkdir /opt/ros/${DISTRIBUTION}/include/ros_rosch
+	fi
+	sudo cp ../include/ros_rosch/publish_counter.h /opt/ros/${DISTRIBUTION}/include/ros_rosch/publish_counter.h
+	sudo cp ../include/ros_rosch/type.h /opt/ros/${DISTRIBUTION}/include/ros_rosch/type.h
+	echo "-------- Set real-time ROS file --------"
+	echo "sudo cp ./devel/lib/libroscpp.so /opt/ros/${DISTRIBUTION}/lib/libroscpp.so"
+	# echo "sudo cp ../include/ros/ros.h /opt/ros/${DISTRIBUTION}/include/ros/ros.h"
+	echo "sudo cp ../include/ros_rosch/publish_counter.h /opt/ros/${DISTRIBUTION}/include/ros_rosch/publish_counter.h"
 fi
 
diff --git a/Scheduler/RT-ROS/script/uninstall b/Scheduler/RT-ROS/script/uninstall
--- a/Scheduler/RT-ROS/script/uninstall
+++ b/Scheduler/RT-ROS/script/uninstall
@@ -2,6 +2,8 @@
 
 echo "-------- Set original file --------"
 
+<< COMMENTOUT
+
 # for Ubuntu 14.04 (indigo)
 if [ -e /opt/ros/indigo/lib/libroscpp.so ]; then
 	echo "sudo cp /opt/ros/indigo/lib/libroscpp.so.backup /opt/ros/indigo/lib/libroscpp.so"
@@ -22,6 +24,32 @@ if [ -e /opt/ros/kinetic/lib/libroscpp.so ]; then
 	if [ -e /opt/ros/kinetic/include/ros_rosch ]; then
 		sudo rm -rf /opt/ros/kinetic/include/ros_rosch
 	fi
+fi
+
+COMMENTOUT
+
+
+
+DISTRIBUTION="NULL"
+
+if [ -e /opt/ros/indigo/lib/libroscpp.so ]; then
+	DISTRIBUTION="indigo"
+elif [ -e /opt/ros/jade/lib/libroscpp.so ]; then
+	DISTRIBUTION="jade"
+elif [ -e /opt/ros/kinetic/lib/libroscpp.so ]; then
+	DISTRIBUTION="kinetic"
+else
+	echo "libroscpp.so does not found"
+	echo "Stop uninstall script"
+	exit 1
+fi
+
+echo "sudo cp /opt/ros/${DISTRIBUTION}/lib/libroscpp.so.backup /opt/ros/${DISTRIBUTION}/lib/libroscpp.so"
+sudo cp /opt/ros/${DISTRIBUTION}/lib/libroscpp.so.backup /opt/ros/${DISTRIBUTION}/lib/libroscpp.so
+echo "sudo cp /opt/ros/${DISTRIBUTION}/include/ros/ros.h.backup /opt/ros/${DISTRIBUTION}/include/ros/ros.h"
+sudo cp /opt/ros/${DISTRIBUTION}/include/ros/ros.h.backup /opt/ros/${DISTRIBUTION}/include/ros/ros.h
+if [ -e /opt/ros/${DISTRIBUTION}/include/ros_rosch ]; then
+	sudo rm -rf /opt/ros/${DISTRIBUTION}/include/ros_rosch
 fi
 
 echo "------------------------------------"
